name: brorun
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.5
  font_awesome_flutter: ^10.4.0
  google_maps_flutter: ^2.5.0

  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
 
flutter:
  uses-material-design: true
  assets:
   - assets/images/Splash.png
   - assets/images/setan.jpg
   - assets/images/aneh.jpg
   - assets/images/
   - assets/icons/
